<?php
require_once __dir__ . '/../lib/data.php';

$dao = \data\dao();
$hash = sha1("password");
$dao->exec("INSERT INTO user (email, password, name) VALUES('admin@example.com', '$hash', 'Joe Doe')");

$dao->exec("INSERT INTO todo (text) VALUES (\"libero. Integer in\"),(\"lobortis ultrices. Vivamus rhoncus.\"),(\"faucibus leo, in lobortis tellus justo sit amet nulla. Donec\"),(\"tellus, imperdiet non, vestibulum nec, euismod in,\"),(\"in,\"),(\"nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing,\"),(\"erat eget\"),(\"eu metus. In lorem.\"),(\"lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus\"),(\"consectetuer ipsum nunc id enim.\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus\"),(\"Morbi vehicula.\"),(\"Aenean massa. Integer vitae nibh.\"),(\"libero at auctor ullamcorper, nisl arcu iaculis enim, sit\"),(\"Duis volutpat\"),(\"cursus et, magna. Praesent interdum ligula\"),(\"lobortis risus. In mi pede, nonummy ut, molestie in, tempus\"),(\"et, commodo at, libero. Morbi\"),(\"consectetuer adipiscing elit. Aliquam auctor, velit\"),(\"Duis cursus, diam at pretium aliquet, metus\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"ligula tortor,\"),(\"odio a purus. Duis elementum, dui quis accumsan convallis,\"),(\"ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor\"),(\"nulla\"),(\"enim commodo hendrerit. Donec porttitor tellus non magna. Nam\"),(\"Ut tincidunt orci quis lectus. Nullam suscipit, est ac\"),(\"arcu. Sed eu nibh vulputate mauris\"),(\"turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis\"),(\"eros nec\"),(\"vel,\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"enim, sit\"),(\"mauris,\"),(\"Vivamus\"),(\"Nunc mauris\"),(\"sed, hendrerit a, arcu. Sed et\"),(\"quam vel sapien\"),(\"nisl elementum purus, accumsan interdum\"),(\"cursus et, eros. Proin ultrices. Duis\"),(\"porttitor tellus non magna.\"),(\"id, erat. Etiam\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"et magnis dis parturient montes, nascetur ridiculus\"),(\"sit amet, risus. Donec nibh enim, gravida sit amet, dapibus\"),(\"tellus. Aenean egestas hendrerit neque.\"),(\"imperdiet\"),(\"mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam\"),(\"orci quis lectus. Nullam suscipit, est ac facilisis facilisis,\"),(\"Duis volutpat nunc\"),(\"Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices\"),(\"risus quis diam luctus lobortis.\"),(\"parturient\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"sit amet, faucibus ut, nulla. Cras eu tellus\"),(\"eget metus. In nec\"),(\"vel arcu eu odio tristique\"),(\"velit dui,\"),(\"justo faucibus\"),(\"Duis\"),(\"euismod ac, fermentum\"),(\"egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede.\"),(\"suscipit\"),(\"felis. Donec tempor, est ac mattis semper, dui lectus\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"fringilla. Donec feugiat metus sit\"),(\"non\"),(\"est ac mattis semper, dui lectus rutrum urna, nec\"),(\"neque non quam. Pellentesque habitant\"),(\"nibh vulputate mauris sagittis placerat. Cras\"),(\"gravida sit amet, dapibus id, blandit at,\"),(\"Cras eu tellus eu augue porttitor interdum.\"),(\"blandit mattis. Cras eget nisi\"),(\"sem\"),(\"ac mattis ornare, lectus\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"odio semper cursus. Integer mollis.\"),(\"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur\"),(\"ullamcorper eu,\"),(\"sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla\"),(\"Donec fringilla. Donec\"),(\"erat. Etiam vestibulum massa rutrum\"),(\"Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae\"),(\"Praesent eu nulla at sem molestie sodales.\"),(\"mattis. Cras eget nisi\"),(\"Nulla\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"blandit congue. In scelerisque scelerisque dui. Suspendisse\"),(\"vitae purus gravida sagittis. Duis\"),(\"velit egestas lacinia. Sed congue, elit sed consequat\"),(\"nisi a odio semper cursus. Integer mollis.\"),(\"egestas nunc sed libero. Proin\"),(\"lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac\"),(\"Nam nulla magna, malesuada vel,\"),(\"Morbi quis urna. Nunc\"),(\"montes, nascetur ridiculus mus. Proin\"),(\"pharetra, felis eget varius ultrices, mauris\")");
$dao->exec("INSERT INTO todo (text) VALUES (\"Quisque porttitor eros nec tellus. Nunc lectus pede,\"),(\"eleifend\"),(\"erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.\"),(\"faucibus leo, in lobortis tellus justo\"),(\"iaculis, lacus\"),(\"litora torquent per conubia nostra, per inceptos\"),(\"In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.\"),(\"sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse\"),(\"senectus et netus et\"),(\"tincidunt orci\")");
